"""
Django settings for spotmaxweb project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from netspot import netspot_settings

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l_p4nzmous5@o09pvy0pvli68@t_l5^pc@236=^jy8swcta_c4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['netspot.maxiv.lu.se', 'netspot']

# AD authentication
AUTH_LDAP_SERVER_URI = netspot_settings.AUTH_LDAP_SERVER_URI
AUTH_LDAP_START_TLS = netspot_settings.AUTH_LDAP_START_TLS
AUTH_LDAP_GLOBAL_OPTIONS = netspot_settings.AUTH_LDAP_GLOBAL_OPTIONS
AUTH_LDAP_BIND_DN = netspot_settings.AUTH_LDAP_BIND_DN
AUTH_LDAP_BIND_PASSWORD = netspot_settings.AUTH_LDAP_BIND_PASSWORD
AUTH_LDAP_USER_SEARCH = netspot_settings.AUTH_LDAP_USER_SEARCH
AUTH_LDAP_CONNECTION_OPTIONS = netspot_settings.AUTH_LDAP_CONNECTION_OPTIONS

# Set up the basic group parameters.
AUTH_LDAP_GROUP_SEARCH = netspot_settings.AUTH_LDAP_GROUP_SEARCH
AUTH_LDAP_GROUP_TYPE = netspot_settings.AUTH_LDAP_GROUP_TYPE
AUTH_LDAP_FIND_GROUP_PERMS = netspot_settings.AUTH_LDAP_FIND_GROUP_PERMS
AUTH_LDAP_REQUIRE_GROUP = netspot_settings.AUTH_LDAP_REQUIRE_GROUP

# Cache group memberships for an hour to minimize LDAP traffic
AUTH_LDAP_CACHE_GROUPS = netspot_settings.AUTH_LDAP_CACHE_GROUPS
AUTH_LDAP_GROUP_CACHE_TIMEOUT = netspot_settings.AUTH_LDAP_GROUP_CACHE_TIMEOUT

AUTHENTICATION_BACKENDS = ['django_auth_ldap.backend.LDAPBackend', 'django.contrib.auth.backends.ModelBackend']

# Cookie age
SESSION_COOKIE_AGE = 900
SESSION_SAVE_EVERY_REQUEST = True

# Login URL
LOGIN_URL = '/login/'

# Temp directory
TEMP_DIRECTORY = '/tmp/netspot/'

# Application definition
INSTALLED_APPS = [
    'netspot.apps.NetspotConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spotmaxweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['netspot/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spotmaxweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = "/usr/share/nginx/spotmaxweb/static"
STATIC_URL = '/static/'

